####################
#### INPUT FILES

genome: "/shared/projects/vietcaf/data/reference/CC1.8_v2_pseudomolecule_cat.fa" # fasta file
test_vcf: "/shared/projects/most_kmer/vcf_bgi_2021/gbp_output/filtered_vcf_by_chrom/vn_final.recode.vcf"
source_vcf: "/shared/projects/most_kmer/vcf_bgi_2021/gbp_output/filtered_vcf_by_chrom/african_final.recode.vcf"
simulate_source: TRUE
source_files: []
test_file: "" # if filled, test_id will be ignored
snp_file: ""
test_id: "@" # "@" for all genotypes or specific id
chromosome: "@" # "@" for all chromosome or specific chroms

####################
#### OUTPUT
outdir: "/shared/projects/elai_most/data/snakelai_out_all"

######################
#### SNP SELECTION
# random_snps: true # random or ordered
# n_batches: 1 # only if "random" split
# batch_size: 1000 # number of snps per batch
# snp_den: [1, 500000] # random selection only, snp density: [nb snps, per kb]. if this object is set, batch_size will be ignored
split_snps_cores: 20
snp_selection:
  even:
    nb_snps: 1 # "all"/integer
    window_size: 5000 # "chrom"/integer
  all:
    nb_snps: "all" # "all"/integer
    window_size: 100000 # "chrom"/integer
# nb_batches: 1 # number of snp sets to be randomly selected


######################
#### SOURCE GENOTYPES SIMULATION
nb_groups: 5
nb_genotypes: 100 # nb of genotypes per group
simulate_cores: 5
simulate_mem_gb: 20

####################
#### ELAI PARAMS
elai: "/shared/projects/vietcaf/scripts/elai/elai-lin" # "/data3/projects/vietcaf/baotram/scripts/elai/elai-lin" # 

elai_params:
  c5_mg20: "-c 5 -mixgen 20 --exclude-nopos --exclude-miss1"
  #c5_mg10_s60: "-c 5 -mixgen 10 -s 60 --exclude-nopos --exclude-miss1"

elai_mem_gb: 20

merged_snps: ["even", "all"]
merged_params: "c5_mg_20"

vcftools: vcftools/0.1.16
singularity: "/shared/projects/vietcaf/scripts/snakelai/singularity-container_myr_4-0-2_rstudio_1.3.sif"
